Repository datasciencecampus/coding-in-the-open, pull requests merged in 2023-06, with the labels that each got.

#28 feat: PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CONTRIBUTING.md
Labels: enhancement

#26 refactor: Style box margins
  assets/styles.css
  docs/assets/styles.css
  docs/sitemap.xml
Labels: documentation

#27 refactor: Renaming subpage dirs & updating links
  README.md
  _quarto.yml
  docs/open-at-the-end/mermaid.css
  docs/search.json
  docs/sitemap.xml
  general-considerations/guidance.qmd
  general-considerations/references.qmd
  index.qmd
  never-open/guidance.qmd
  open-at-the-end/guidance.qmd
  open-at-the-end/mermaid.css
  open-at-the-end/process-chart.qmd
  open-at-the-end/risk-table.qmd
  open-at-the-start/guidance.qmd
  what-could-go-wrong/checklist.qmd
Labels: enhancement

#38 Fixing PR Template location
  .github/pull_request_template.md
Labels: bug

#39 fix: corrected duplicate hyperlink
  bibliography/references.bib
Labels: bug
