Repository datasciencecampus/coding-in-the-open, pull requests merged in 2023-05, with the labels that each got.

#4 WIP CI workflow
  .github/workflows/quarto-publish.yml
  .gitignore
  _quarto.yml
  quarto-publish.yml
Labels: enhancement

#8 Create bug_report.md
  .github/workflows/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#9 3 nhs guidance is buried
  bibliography/references.bib
  docs/search.json
  docs/sitemap.xml
  index.qmd
Labels: help wanted

#12 docs: Including notes on CI config in readme
  README.md
Labels: documentation

#5 Adding more detail to the private to public
  README.md
  _quarto.yml
  assets/images/risk-exposure-diagram.png
  bibliography/references.bib
  common/general_considerations.qmd
  docs/assets/images/risk-exposure-diagram.png
  docs/private_to_public/mermaid.css
  docs/search.json
  docs/sitemap.xml
  index.qmd
  open-development/open-at-start.qmd
  private/private-development.qmd
  private_to_public/guidance.qmd
  private_to_public/mermaid.css
  private_to_public/process-chart.qmd
  private_to_public/risk-table.qmd
  www-ebi/resolving-problems.qmd
Labels: enhancement

#13 10 accessibility issues
  _quarto.yml
  docs/search.json
  docs/site_libs/bootstrap/bootstrap.min.css
  docs/site_libs/quarto-search/autocomplete.umd.js
  docs/site_libs/quarto-search/fuse.min.js
  docs/site_libs/quarto-search/quarto-search.js
  docs/sitemap.xml
  index.qmd
Labels: enhancement, help wanted

#20 feat: Linking to visio process chart
  assets/images/WIP_private_to_public_guidance_flowchart.png
  docs/assets/images/WIP_private_to_public_guidance_flowchart.png
  docs/search.json
  docs/sitemap.xml
  private_to_public/process-chart.qmd
Labels: enhancement

#22 updated img tag process chart
  README.md
  docs/sitemap.xml
  private_to_public/process-chart.qmd
Labels: bug, accessibility

#23 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement
